### ISSUE TITLE
Can't Get A GG2SMS Port to work

### ISSUE THREAD

**Issue by DemonDezerin** [CatmanFan/FriishProduce#52]
I'm trying to put Tails Adventure GG2SMS on The Wii VC and It Won't Work it keeps saying it's to big

**Comment by saulfabregwiivc** [comment]
It's because SEGA Master System rom size limit currently is set by FriishProduce to 512 kB, and Tails' Adventure GG2SMS hack is 1 MB.
I'll try manually injecting the game if the game boots on VC.

**Comment by DemonDezerin** [comment]
I have the ROM On Hand if you need it

**Comment by saulfabregwiivc** [comment]
Fixed as of https://github.com/CatmanFan/FriishProduce/commit/b6b9930fef058c5f5911d85de26548e5d5de661b.

Btw, if by any reason you want to try with roms more larger than the max size supported by VC (which it could cause more crashes), @CatmanFan added an option for skip the max ROM size check of FriishProduce in this commit:
https://github.com/CatmanFan/FriishProduce/commit/a0c25965a03b9f898fbc83fdcb99594bf4943898

(Beware that this only works for FriishProduce, because every single internal VC emulator handle their own max rom size limits.)

**Comment by saulfabregwiivc** [comment]
Fixed as of https://github.com/CatmanFan/FriishProduce/commit/b6b9930fef058c5f5911d85de26548e5d5de661b.

Btw, if by any reason you want to try with roms more larger than the max size supported by VC (which it could cause more crashes), @CatmanFan added an option for skip the max ROM size check of FriishProduce in this commit:
https://github.com/CatmanFan/FriishProduce/commit/a0c25965a03b9f898fbc83fdcb99594bf4943898

(Beware that this only works for FriishProduce, because every single internal VC emulator handle their own max rom size limits.)

**Comment by DemonDezerin** [comment]
Awesome, thanks!

**Comment by DemonDezerin** [comment]
how do i compile it or you could send me a built copy

**Comment by saulfabregwiivc** [comment]
To compile FriishProduce you need to have installed **Visual Studio 2019** as well as **Microsoft .NET Framework 4.7.2** on your computer.

Or if you prefer, i can compile a version of FriishProduce with latest changes.

**Comment by DemonDezerin** [comment]
Yes, please!

**Comment by DemonDezerin** [comment]
Here's an idea make it so you can have the bios if u provide it plz

**Comment by CatmanFan** [comment]
> Here's an idea make it so you can have the bios if u provide it plz
The BIOS is not supported by the Virtual Console emulator itself, but it should be an option for Genesis Plus GX or other Gen/MD emulators.

By the way, the ROM itself should be working without issues.

**Comment by DemonDezerin** [comment]
Thanks but if I may ask where is the build with the fixed 1 MB limitation
if you don’t mind me asking?

**Comment by DemonDezerin** [comment]
I can't even install .net so I can compile it 😢

**Comment by DemonDezerin** [comment]
I need a build

**Comment by CatmanFan** [comment]
> Thanks but if I may ask where is the build with the fixed 1 MB limitation if you don’t mind me asking?

Crap, I forgot to respond earlier.

[Here you go](https://mega.nz/file/B05jXAJT#gW9rAg26W35ubsW_Nl_PLWshUkHwAf5pMaLEQtzTQ4U). It's still kind of WIP, though

**Comment by DemonDezerin** [comment]
Well now it won’t even let me export it I have the option enabled

**Comment by DemonDezerin** [comment]
Nevermind I didn’t put a wad in

**Comment by DemonDezerin** [comment]
now my copy wont connest to the internet its getting kinda annoying
